global:
  resolve_timeout: 5m

route:
  receiver: "default"
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "default"
    email_configs:
      - to: "your@email.com"
        from: "alertmanager@yourdomain.com"
        smarthost: "smtp.yourdomain.com:587"
        auth_username: "alertmanager@yourdomain.com"
        auth_password: "yourpassword"
        auth_identity: "alertmanager@yourdomain.com"
