global:
  resolve_timeout: 5m

route:
  receiver: slack-notifications
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: slack-notifications
    slack_configs:
      - channel: "#alerts"
        send_resolved: true
        username: "Prometheus"
        title: "{{ .CommonLabels.alertname }}"
        text: >-
          *Alert:* {{ .CommonLabels.alertname }}  
          *Severity:* {{ .CommonLabels.severity }}  
          *Instance:* {{ .CommonLabels.instance }}
        api_url: "https://hooks.slack.com/services/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"
