groups:
  - name: example_alertss
    rules:
      - alert: HighCPUUsage
        expr: node_cpu_seconds_total{mode="user"} > 0.8
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes."

      - alert: DiskSpaceLow
        expr: node_filesystem_avail_bytes / node_filesystem_size_bytes < 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Available disk space is below 10%."
