apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-service
  namespace: monitoring
  labels:
    app: blackbox-exporter
spec:
  selector:
    app: blackbox-exporter
  ports:
    - protocol: TCP
      port: 9115
      targetPort: 9115
      name: http
  type: ClusterIP
